[shell]
program = "/bin/zsh"
args = ["-1"]

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
# padding = { x = 10 , y = 10 } 
decorations = "None"

[font]
normal = { family = "HackNerdFont", style = "Regular" }
size = 24

[cursor]
style = { shape = "Block", blinking = "Never" }
